<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="#localstyle" type="text/css"?>

<!DOCTYPE guttext [

<!ENTITY title "The Madman:  His Parables and Poems">
<!ENTITY author "Kahlil Gibran">
<!ENTITY lifespan "">
<!ENTITY fullguttitle "The Project Gutenberg Etext of &title;, by &author;">
<!ENTITY textnum "5616">
<!ENTITY releasedate "May, 2004">
<!ENTITY postdate "07/22/2002">
<!ENTITY edition "10">
<!ENTITY nextedition "11">
<!ENTITY version "x">
<!ENTITY nextversion "a">
<!ENTITY language "English">
<!ENTITY filebase "thmdm">
<!ENTITY credit "Typed and proofread by Brett Fishburne (william.fishburne@verizon.net)">


<!ELEMENT guttext (gutstyle,(gutmeta|markupmeta),(book|play|poem|document)*,endgutmeta?)>

<!ELEMENT gutstyle (#PCDATA)*>
<!ATTLIST gutstyle
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT gutmeta (#PCDATA|para|legal|simplesect|title|markupmeta)*>	<!-- Put all info related to Project Gutenberg in here -->

<!ELEMENT markupmeta (#PCDATA|textnum|preparer|gutfilename|gutdate|title|author|edition|language|para|legal|simplesect)*>	

<!ELEMENT legal (#PCDATA|line)*>							<!-- Put all text-specific info in here -->

<!ELEMENT endgutmeta (#PCDATA|para|simplesect|title)*>

<!-- ******************** METADATA ELEMENTS ********************** -->

<!ELEMENT textnum (#PCDATA|quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>		<!-- Put the Gutenberg E-text number in here -->
<!ATTLIST textnum
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>
	
<!ELEMENT preparer (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>		<!-- Use for "prepared, proofread, or scanned by -->
<!ATTLIST preparer
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>
				
<!ELEMENT gutdate (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>		<!-- Use Gutenberg date (when added to collection -->
<!ATTLIST gutdate
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT gutfilename (#PCDATA|verse|title |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>	<!-- Use "This file should be named&#8230;" -->
<!ATTLIST gutfilename
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!-- ******************** TOP LEVEL ELEMENTS ********************** -->

<!-- The text can be any of the following elements -->
<!ELEMENT book (acknowledge?,meta*,frontmatter?,bookbody,backmatter?,endmeta*)>
<!ELEMENT play (acknowledge?,meta*,frontmatter?,playbody,backmatter?,endmeta*)>
<!ELEMENT poem (acknowledge?,meta*,toc*,(poembody|simplesect|para)*,endmeta*)>
<!ELEMENT document (acknowledge?,meta*,frontmatter?,documentbody,backmatter?,endmeta*)> 

<!-- ***************** TOP LEVEL ELEMENT DECLARATIONS ******************* -->

<!ELEMENT acknowledge (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST acknowledge
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT meta EMPTY>
<!ATTLIST meta
   content  CDATA  #REQUIRED
   id       ID     #IMPLIED
>

<!ELEMENT endmeta EMPTY >
<!ATTLIST endmeta
   content  CDATA  #REQUIRED
   id       ID     #IMPLIED
>

<!ELEMENT bookbody (part*|chapter*)>
<!ELEMENT poembody ((prenote|title)*,(author|prose|subtitle|verse|line|para|tune|note|footnote)*)>
<!ELEMENT playbody (part|act|scene)*>
<!ELEMENT documentbody ((prenote|title)*,(speech|para|note|misc*))> 


<!ELEMENT backmatter ((appendix|index|glossary|biblio|note)*,colophon?)>


<!-- ***************** END TOP LEVEL ELEMENT DECLARATIONS ******************* -->


<!-- ***************** BEGIN FRONTMATTER ELEMENT DECLARATIONS ******************* -->

<!ELEMENT frontmatter (htitlepage|copypage|epigraph|titlepage|
                toc|acksect|dedication|preface|prologue|personae|introduction|miscfm)*>

<!ELEMENT htitlepage (#PCDATA|title|subtitle|author|para|poembody|song |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST htitlepage
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT copypage (#PCDATA|para|poembody|song|note |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST copypage
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT epigraph (#PCDATA|para|poembody|song|note|blockquote |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST epigraph
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT titlepage (#PCDATA|partnum|title|subtitle|author|pubinfo|para|poembody|song|note|line |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST titlepage
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT partnum (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST partnum
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT pubinfo (#PCDATA|para|line |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST pubinfo
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT toc (#PCDATA|title|subtitle|subsubtitle|item|list|deflist |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST toc
  toctype (contents|maps|graphics|tables|other) "contents" 
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT acksect (#PCDATA|para|poembody|song|note |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST acksect
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT dedication (#PCDATA|title|para|poembody|song|note |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST dedication
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT preface ((title|chapheader)?,(para|poembody|song|sect1|simplesect |letter|blockquote|footnote|note|list|deflist|table|blockgraphic)*,endchap?,preauthor?)>
<!ATTLIST preface  ref   IDREF  #IMPLIED
id    ID     #IMPLIED
type  CDATA  #IMPLIED
role  CDATA  #IMPLIED
class CDATA  #IMPLIED
>

<!ELEMENT prologue ((title|chapheader)?,(para|poembody|song|simplesect |letter|blockquote|footnote|note|list|deflist|table|blockgraphic)*,endchap?,preauthor?)>
<!ATTLIST prologue ref   IDREF  #IMPLIED
id    ID     #IMPLIED
type  CDATA  #IMPLIED
role  CDATA  #IMPLIED
class CDATA  #IMPLIED
>

<!ELEMENT personae (#PCDATA|title|pgroup|persona|para|note |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST personae ref   IDREF  #IMPLIED
id    ID     #IMPLIED
type  CDATA  #IMPLIED
role  CDATA  #IMPLIED
class CDATA  #IMPLIED
>

<!ELEMENT introduction ((title|chapheader)?,(para|poembody|song|sect1|simplesect |letter|blockquote|footnote|note|list|deflist|table|blockgraphic)*,endchap?)>
<!ATTLIST introduction  ref   IDREF  #IMPLIED
id    ID     #IMPLIED
type  CDATA  #IMPLIED
role  CDATA  #IMPLIED
class CDATA  #IMPLIED
>

<!ELEMENT miscfm (#PCDATA|para|poembody|song|verse|note |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST miscfm
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT preauthor (#PCDATA|author |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST preauthor
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!-- ***************** END FRONTMATTER ELEMENT DECLARATIONS ******************* -->


<!-- ***************** BEGIN BODY ELEMENT DECLARATIONS ******************* -->
<!-- BOOKBODY (part|chapter) -->
<!-- PLAYBODY (scene|part|act) -->
<!-- POEMBODY (prenote, title, author|prose|subtitle|tune|note|footnote|verse) -->
<!-- DOCUMENTBODY (prenote|title, speech|para|note|misc) -->

<!ELEMENT part (acknowledge?,(titlepage|toc|htitlepage|act|prose)*,chapter*)>
<!ATTLIST part
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT chapter ((title|chapheader)?,(para|poembody|playbody|song|sect1|simplesect|page |letter|blockquote|footnote|note|list|deflist|table|blockgraphic)*,endchap?)>
<!ATTLIST chapter  ref   IDREF  #IMPLIED
id    ID     #IMPLIED
type  CDATA  #IMPLIED
role  CDATA  #IMPLIED
class CDATA  #IMPLIED
>

<!ELEMENT act (title|scene|speech|poembody|playbody|song|scndesc|stagedir|prose|note)*>
<!ATTLIST act ref   IDREF  #IMPLIED
id    ID     #IMPLIED
type  CDATA  #IMPLIED
role  CDATA  #IMPLIED
class CDATA  #IMPLIED
>

<!ELEMENT prenote (#PCDATA)>
<!ATTLIST prenote ref   IDREF  #IMPLIED
id    ID     #IMPLIED
type  CDATA  #IMPLIED
role  CDATA  #IMPLIED
class CDATA  #IMPLIED
>

<!ELEMENT title (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST title
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT author (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST author
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT edition (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST edition
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT language (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST language
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT prose (#PCDATA|title|simplesect|para |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST prose ref   IDREF  #IMPLIED
id    ID     #IMPLIED
type  CDATA  #IMPLIED
role  CDATA  #IMPLIED
class CDATA  #IMPLIED
>

<!ELEMENT subtitle (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST subtitle
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT tune (#PCDATA)>
<!ATTLIST tune ref   IDREF  #IMPLIED
id    ID     #IMPLIED
type  CDATA  #IMPLIED
role  CDATA  #IMPLIED
class CDATA  #IMPLIED
>

<!ELEMENT verse (title|subtitle|line|note)*>
<!ATTLIST verse
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>


<!-- ***************** BEGIN LOWERLEVEL ELEMENT DECLARATIONS ******************* -->

<!ELEMENT subsubtitle (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST subsubtitle
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT chapheader (title|subtitle|chapnum|chapsummary|blockquote|para|note)*>
<!ATTLIST chapheader
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT chapnum (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST chapnum
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT chapsummary (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST chapsummary
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT endchap (para |letter|blockquote|footnote|note|list|deflist|table|blockgraphic)*>
<!ATTLIST endchap  ref   IDREF  #IMPLIED
id    ID     #IMPLIED
type  CDATA  #IMPLIED
role  CDATA  #IMPLIED
class CDATA  #IMPLIED
>

<!ELEMENT attrib (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST attrib
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT caption (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST caption
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT song (#PCDATA|title|subtitle|verse|line|note|footnote |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST song
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT line (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST line
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT para (#PCDATA|title |quote|emph|ital|smcaps|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST para
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT simplesect (title,(subtitle|para|poembody|song |letter|blockquote|footnote|note|list|deflist|table|blockgraphic)*)>
<!ATTLIST simplesect
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT sect1 (title,(sect2|simplesect|para|poembody|song |letter|blockquote|footnote|note|list|deflist|table|blockgraphic)*)>
<!ATTLIST sect1
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT sect2 (title,(sect3|simplesect|subtitle|para|poembody|song  |letter|blockquote|footnote|note|list|deflist|table|blockgraphic)*)>
<!ATTLIST sect2
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT sect3 (title,(sect4|simplesect|subtitle|para|poembody|song  |letter|blockquote|footnote|note|list|deflist|table|blockgraphic)*)>
<!ATTLIST sect3
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT sect4 (title,(simplesect|subtitle|para|poembody|song  |letter|blockquote|footnote|note|list|deflist|table|blockgraphic)*)>
<!ATTLIST sect4
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT page (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST page
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>


<!-- start play elements -->

<!ELEMENT speech (#PCDATA|speaker|stagedir|song|poembody|line  |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST speech ref   IDREF  #IMPLIED
id    ID     #IMPLIED
type  CDATA  #IMPLIED
role  CDATA  #IMPLIED
class CDATA  #IMPLIED
>

<!ELEMENT scene (title|speech|poembody|song|scndesc|stagedir|prose|note)*>
<!ATTLIST scene ref   IDREF  #IMPLIED
id    ID     #IMPLIED
type  CDATA  #IMPLIED
role  CDATA  #IMPLIED
class CDATA  #IMPLIED
>

<!ELEMENT speaker (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST speaker ref   IDREF  #IMPLIED
id    ID     #IMPLIED
type  CDATA  #IMPLIED
role  CDATA  #IMPLIED
class CDATA  #IMPLIED
>

<!ELEMENT scndesc (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST scndesc ref   IDREF  #IMPLIED
id    ID     #IMPLIED
type  CDATA  #IMPLIED
role  CDATA  #IMPLIED
class CDATA  #IMPLIED
>

<!ELEMENT stagedir (#PCDATA  |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST stagedir ref   IDREF  #IMPLIED
id    ID     #IMPLIED
type  CDATA  #IMPLIED
role  CDATA  #IMPLIED
class CDATA  #IMPLIED
>

<!ELEMENT pgroup (#PCDATA|title|persona|para|note |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST pgroup  ref   IDREF  #IMPLIED
id    ID     #IMPLIED
type  CDATA  #IMPLIED
role  CDATA  #IMPLIED
class CDATA  #IMPLIED
>

<!ELEMENT persona (#PCDATA|actor|actress |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST persona  ref   IDREF  #IMPLIED
id    ID     #IMPLIED
type  CDATA  #IMPLIED
role  CDATA  #IMPLIED
class CDATA  #IMPLIED
>

<!ELEMENT actor (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST actor ref   IDREF  #IMPLIED
id    ID     #IMPLIED
type  CDATA  #IMPLIED
role  CDATA  #IMPLIED
class CDATA  #IMPLIED
>

<!ELEMENT actress (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST actress ref   IDREF  #IMPLIED
id    ID     #IMPLIED
type  CDATA  #IMPLIED
role  CDATA  #IMPLIED
class CDATA  #IMPLIED
>

<!-- end play elements -->


<!-- ***************** BEGIN BACKMATTER ELEMENT DECLARATIONS ******************* -->

<!ELEMENT index (title|item|list|deflist|note)*>
<!ATTLIST index
  indtype (contents|authors|firstlines|tables|other) "contents" 
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT glossary (title|item|list|deflist|note)*>
<!ATTLIST glossary  
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT biblio (title|item|list|deflist|note)*>
<!ATTLIST biblio  
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT appendix ((title|chapheader)?,(para|poembody|song|sect1|simplesect |letter|blockquote|footnote|note|list|deflist|table|blockgraphic)*,endchap?)>
<!ATTLIST appendix  ref   IDREF  #IMPLIED
id    ID     #IMPLIED
type  CDATA  #IMPLIED
role  CDATA  #IMPLIED
class CDATA  #IMPLIED
>

<!ELEMENT colophon (#PCDATA|para|poembody|song |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST colophon
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>


<!-- the block elements -->

<!-- letter elements, a block element -->

<!ELEMENT letter (address|to|from|salut|sig|title|subtitle|para|poembody|song|line|note)*>
<!ATTLIST letter
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT address (#PCDATA|para|line |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST address
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT to (#PCDATA|para|line |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST to
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT from (#PCDATA|para|line |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST from
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT salut (#PCDATA|para|line |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST salut
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT sig (#PCDATA|para|line |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST sig
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>
<!-- end letter elements-->

<!ELEMENT blockquote (title?,(para|poembody|song)*,attrib?)>
<!ATTLIST blockquote
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT footnote (#PCDATA |quote|emph|ital|smcaps|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST footnote
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT note (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST note
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!-- list elements, a block element -->

<!ELEMENT list (title?,(list|item)*)>
<!ATTLIST list
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT item (#PCDATA|para|poembody|song|simplesect |letter|blockquote|footnote|note|list|deflist|table|blockgraphic |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST item
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT deflist (title?,(item,desc?,def*)*)>
<!ATTLIST deflist
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT desc (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST desc
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT def (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST def
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!-- end list elements -->


<!-- table elements, a block element -->

<!ELEMENT table (title?,row*,caption?)>
<!ATTLIST table
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT row (cell)*>
<!ATTLIST row
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT cell (#PCDATA |letter|blockquote|footnote|note|list|deflist|table|blockgraphic |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST cell
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!--end table elements-->


<!--graphics-->

<!-- an inline element, description required -->
<!ELEMENT graphic EMPTY >
<!ATTLIST graphic
  desc CDATA #REQUIRED
  href CDATA #REQUIRED
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!-- a block element -->
<!ELEMENT blockgraphic (title?,graphic,caption?)>
<!ATTLIST blockgraphic
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>


<!-- the inline elements-->

<!ELEMENT quote (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST quote
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT emph (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST emph
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT ital (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST ital
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT smcaps (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST smcaps
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT reference (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST reference
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT date (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST date
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT place (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST place
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT name (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST name
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!-- inline error elements, use to enclose or note potential errors in text -->

<!ELEMENT txterr (#PCDATA)*>
<!ATTLIST txterr
  explain  CDATA  #IMPLIED
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!--an explanation is required-->
<!ELEMENT mkuperr EMPTY>
<!ATTLIST mkuperr
  explain  CDATA  #REQUIRED
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>

<!ELEMENT misc (#PCDATA |quote|emph|ital|reference|date|place|name|graphic|txterr|mkuperr|misc)*>
<!ATTLIST misc
  ref   IDREF  #IMPLIED
  id    ID     #IMPLIED
  type  CDATA  #IMPLIED
  role  CDATA  #IMPLIED
  class CDATA  #IMPLIED
>
<!-- end inline elements -->


<!-- END DTD -->
]
>

<guttext>

<gutstyle id="localstyle">

GUTTEXT{font-family:"Courier New", Courier, sans-serif;margin-top:24pt;margin-bottom:24pt;}

GUTSTYLE{display:none}

GUTMETA{display:block;font-family:"Courier New", Courier, sans-serif;margin-top:24pt;margin-bottom:24pt;}

MARKUPMETA{display:block;font-family:"Courier New", Courier, sans-serif;margin-top:24pt;margin-bottom:24pt;}

MARKUPMETA TITLE{display:block;font-family:"Courier New", Courier, sans-serif;font-weight:normal;font-size:12pt;margin:0;font-weight:400;}

GUTFILENAME{display:block;font-family:"Courier New", Courier, sans-serif;margin-top:24pt;margin-bottom:24pt;}

GUTFILENAME TITLE{display:block;font-family:"Courier New", Courier, sans-serif;font-weight:normal;font-size:12pt;margin:0;font-weight:400;}

LEGAL{display:block;font-family:courier;font-weight:normal;font-size:12pt;}

ENDGUTMETA{display:block;font-family:"Courier New", Courier, sans-serif;margin-top:24pt;margin-bottom:24pt;}

BOOK{display:block;font-family:"Courier New", Courier, sans-serif;margin-top:24pt;margin-bottom:24pt;}

PLAY{display:block;font-family:"Courier New", Courier, sans-serif;margin-top:24pt;margin-bottom:24pt;}

POEM{display:block;font-family:"Courier New", Courier, sans-serif;margin-top:24pt;margin-bottom:24pt;}

DOCUMENT{display:block;font-family:"Courier New", Courier, sans-serif;margin-top:24pt;margin-bottom:24pt;}

ACKNOWLEDGE{display:block;font-family:"Courier New", Courier, sans-serif;margin-top:24pt;margin-bottom:24pt;}

META{display:block;font-family:"Courier New", Courier, sans-serif;margin-top:24pt;margin-bottom:24pt;}

ENDMETA{display:none;}

BOOKBODY{display:block;font-family:"Courier New", Courier, sans-serif;margin-top:24pt;margin-bottom:24pt;}

POEMBODY{display:block;font-family:"Courier New", Courier, sans-serif;margin-top:24pt;margin-bottom:24pt;}

PLAYBODY{display:block;font-family:"Courier New", Courier, sans-serif;margin-top:24pt;margin-bottom:24pt;}

DOCUMENTBODY{display:block;font-family:"Courier New", Courier, sans-serif;margin-top:24pt;margin-bottom:24pt;}

BACKMATTER{display:block;font-family:"Courier New", Courier, sans-serif;margin-top:24pt;margin-bottom:24pt;}

FRONTMATTER{display:block;font-family:"Courier New", Courier, sans-serif;margin-top:24pt;margin-bottom:24pt;}

HTITLEPAGE{display:block;text-align:center;font-family:"Courier New", Courier, sans-serif;margin-top:24pt;margin-bottom:24pt;}
